server:
  port: 7777

spring:
  application:
    name: l04_jpa_km_coding
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
#    username: system
#    password: oracle
    username: km_coding
    password: km_codingpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect