spring:
  config:
    activate:
      on-profile: depoly
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: my-real-bucket
    region:
      static: ap-northeast-2
