server:
  port: 7777

spring:
  application:
    name: l04_jpa_km_coding
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
#    username: system
#    password: oracle
    username: km_coding
    password: km_codingpw
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
        highlight_sql: true
  profiles:
    active: local
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 1MB
# 	•	enabled: Enables multipart (file upload) support in Spring.
#   •	max-file-size: Maximum size allowed for a single uploaded file.
#	•	max-request-size: Maximum total size allowed for the entire upload request.
#	•	file-size-threshold: File size at which Spring begins writing data to disk instead of memory.
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
